{
 "title": "工作负载详情监控 - KubePolaris",
 "tags": [
  "kubernetes",
  "workload",
  "container"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "deployment_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "podname",
    "label": "Workload",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$deployment_namespace\"}, deployment)"
    }
   },
   { "name": "Interface", "label": "Interface", "query": "eth0,eth1" },
   { "name": "Intervals", "query": "1m,2m,3m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\"}[$Intervals])) by(pod) /( sum (kube_pod_container_resource_limits{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",resource=\"cpu\"}) by(pod) ) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory 使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",container!=\"POD\"}) by(pod)/sum(kube_pod_container_resource_limits{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",resource=\"memory\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO Read - QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",container !=\"POD\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO Write - QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",container!=\"POD\"}[$Intervals])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU 核限制",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",resource=\"cpu\"})/count(kube_pod_container_resource_limits{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "内存限制",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",resource=\"memory\"})/count(kube_pod_container_resource_limits{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "容器整体可用率",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"$podname\",namespace=\"$deployment_namespace\"} / kube_deployment_spec_replicas{deployment=\"$podname\",namespace=\"$deployment_namespace\"} * 100"
    }
   ]
  },
  {
   "title": "健康检查失败次数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prober_probe_total{namespace=\"$deployment_namespace\",pod=~\"$podname-.*\",probe_type=\"Readiness\",result=\"failed\"}[60s])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "容器重启情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$deployment_namespace\",pod=~\"$podname-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Incoming on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",interface=~\"$Interface.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Outgoing on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",interface=~\"$Interface.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Input PPS on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",interface=~\"$Interface.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Output PPS on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",interface=~\"$Interface.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "文件句柄打开数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_file_descriptors{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\",container!=\"POD\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_threads{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"POD\",container!=\"\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Input Droped on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",interface=~\"$Interface.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Output Droped on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",interface=~\"$Interface.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU限流比例",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_periods_total{pod=~\"$podname.*\",container!=\"\",namespace=\"$deployment_namespace\"}[1m])) by (pod) / sum(irate(container_cpu_cfs_periods_total{pod=~\"$podname.*\",container!=\"\",namespace=\"$deployment_namespace\"}[1m]) * 100) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU 节流时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$deployment_namespace\",pod=~\"$podname.*\",container!=\"\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}