{
 "title": "Pod 详情监控 - KubePolaris",
 "tags": [
  "kubernetes",
  "pod",
  "container"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "podname",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   },
   { "name": "Interface", "label": "Interface", "query": "eth0,eth1" },
   { "name": "Intervals", "query": "1m,2m,3m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "CPU 使用率 (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=\"$podname\",container!=\"\"}[$Intervals])) by(container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",resource=\"cpu\"}) by(container) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory 使用率 (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",container!=\"POD\"}) by(container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",resource=\"memory\"}) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "IO Read (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",container!=\"POD\"}[1m])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "IO Write (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",container!=\"POD\"}[$Intervals])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU 核限制",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "内存限制",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "容器重启次数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$podname\"})"
    }
   ]
  },
  {
   "title": "健康检查失败次数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prober_probe_total{namespace=\"$namespace\",pod=\"$podname\",probe_type=\"Readiness\",result=\"failed\"}[60s])*60) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "容器重启情况 (按容器)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$podname\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network Incoming on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$podname\",interface=~\"$Interface.*\"}[$__rate_interval]))",
     "legendFormat": "接收"
    }
   ]
  },
  {
   "title": "Network Outgoing on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$podname\",interface=~\"$Interface.*\"}[$__rate_interval]))",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "Network Input PPS on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$podname\",interface=~\"$Interface.*\"}[$__rate_interval]))",
     "legendFormat": "接收"
    }
   ]
  },
  {
   "title": "Network Output PPS on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$podname\",interface=~\"$Interface.*\"}[$__rate_interval]))",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "文件句柄打开数 (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_file_descriptors{namespace=\"$namespace\",pod=\"$podname\",container!=\"\",container!=\"POD\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Running Threads (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_threads{namespace=\"$namespace\",pod=\"$podname\",container!=\"POD\",container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network Input Dropped on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$podname\",interface=~\"$Interface.*\"}[$__rate_interval]))",
     "legendFormat": "接收丢包"
    }
   ]
  },
  {
   "title": "Network Output Dropped on $Interface",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\",pod=\"$podname\",interface=~\"$Interface.*\"}[$__rate_interval]))",
     "legendFormat": "发送丢包"
    }
   ]
  },
  {
   "title": "CPU限流比例 (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_periods_total{pod=\"$podname\",container!=\"\",namespace=\"$namespace\"}[1m])) by(container) / sum(irate(container_cpu_cfs_periods_total{pod=\"$podname\",container!=\"\",namespace=\"$namespace\"}[1m]) * 100) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU 节流时间 (按容器)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",pod=\"$podname\",container!=\"\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}